"""add assignment model

Revision ID: aa56aee5acf8
Revises: 9dfa2a9d7f39
Create Date: 2019-07-07 22:35:03.276765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa56aee5acf8'
down_revision = '9dfa2a9d7f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestant_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_model')
    # ### end Alembic commands ###
