"""add status in calender

Revision ID: af4d2ff12524
Revises: 3a3c438bb577
Create Date: 2019-06-17 11:13:34.816566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af4d2ff12524'
down_revision = '3a3c438bb577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calender_model', sa.Column('status', mysql.ENUM('applying', 'design_1st_submitting', 'design_1st_announcing', 'waiting_for_contest', 'contesting', 'final_submitting', 'end'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calender_model', 'status')
    # ### end Alembic commands ###
