"""currect the lunch_number name

Revision ID: ca80e269779f
Revises: da844f358887
Create Date: 2019-06-30 20:32:43.204799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = 'ca80e269779f'
down_revision = 'da844f358887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestant_model', sa.Column('lunch_number', sa.Integer(), nullable=False))
    conn = op.get_bind()
    conn.execute(
        text(
            """
                update contestant_model
                set lunch_number = launch_number
            """
        )
    )
    op.drop_column('contestant_model', 'launch_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestant_model', sa.Column('launch_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('contestant_model', 'lunch_number')
    # ### end Alembic commands ###
