"""create ticket number

Revision ID: cce0c325d57d
Revises: aa56aee5acf8
Create Date: 2019-07-19 00:59:00.231734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce0c325d57d'
down_revision = 'aa56aee5acf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_number_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestant_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_number_model')
    # ### end Alembic commands ###
