"""currect the birth type

Revision ID: da844f358887
Revises: 8af701a84a34
Create Date: 2019-06-30 01:35:40.571978

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da844f358887'
down_revision = '8af701a84a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contestant_model', 'birth',
                    existing_type=mysql.DATE,
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contestant_model', 'birth',
                    existing_type=mysql.DATETIME,
                    nullable=False)
    # ### end Alembic commands ###
